name: Docker Image CI
### workflow will run on push
on:
  push:
    branches: [ "master" ]
    
  pull_request:
   branches: ["master"]
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    # Build the Docker image from the Dockerfile in the repository
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: croates23/hangmanfinal:latest
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: croates23/hangmanfinal:latest
