name: starter pipeline

#This on clause specifies which event this pipeline will run
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
  workflow_dispatch:
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      -name: say hello
      run: echo "Hey,worlddd"
    
